---
- name: Update apt repo
  apt:
    update_cache: yes

- name: Update packages
  apt:
    pkg:
      - libffi-dev
      - libssl-dev
      - python3-dev
      - python3
      - python3-pip

- name: Install docker-compose
  pip:
    name: docker-compose